AWSTemplateFormatVersion: "2010-09-09"
Description: >
  alarm-craft integration tests


Resources:
  Enrironment:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: environment/template.yaml
      Tags:
      - Key: Owner
        Value: alarm-craft-integ-test

  AlarmCraftToolExecution:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: codebuild/template.yaml
      Parameters:
        CodeBuildName: "alarm-craft-integ-test-codebuild"
        EventName: "alarm-craft-integ-test-eventbridge"
        AlarmConfigRepositoryType: GITHUB
        AlarmConfigRepositoryCloneUrl: "https://github.com/ryo-murai/alarm-craft-integration-tests.git"
        BranchNameAlarmConfig: "main"
        EventSourceCfnStackNamePrefix: !Sub "${AWS::StackName}-Enrironment"
        AlarmNotifSNSTopicArn: !GetAtt TestCases.Outputs.TopicArn
        LogGroupRetentionInDays: "1"

  TestCases:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: tests/template.yaml
      Parameters:
        RestApiId: !GetAtt Enrironment.Outputs.RestApiId
        LambdaStandaloneFunctionArn: !GetAtt Enrironment.Outputs.LambdaStandaloneFunctionArn


  