AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Alarm Craft Test Environment

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 128
    Timeout: 5

Resources:
  StandaloneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "acmr-lambda-standalone"
      Handler: index.always_error
      InlineCode: |
        def always_error(event, context):
          raise Exception("error")

  RestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "acmr-lambda-restapi"
      Handler: 'index.resp500'
      InlineCode: |
        def resp500(event, context):
          return {"statusCode": 500}
      Events:
        RestApiInvocationEvent:
          Type: Api
          Properties:
            Path: /execute
            Method: get
            RestApiId: !Ref RestAPI

  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: "acmr-apigateway-rest"
      StageName: "api"
      EndpointConfiguration:
        Type: REGIONAL
      DisableExecuteApiEndpoint: false

Outputs:
  RestApiId:
    Value: !Ref RestAPI
  LambdaStandaloneFunctionArn:
    Value: !GetAtt StandaloneFunction.Arn
